"""empty message

Revision ID: 7a3cf14d09f9
Revises: 8ae721ecc756
Create Date: 2020-09-23 16:08:32.023658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a3cf14d09f9'
down_revision = '8ae721ecc756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('api_key', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'usuario', ['api_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='unique')
    op.drop_column('usuario', 'api_key')
    # ### end Alembic commands ###
